version: "3"
services:
  bitcoind:
    image: coblox/bitcoin-core:0.17.0
    command: -regtest
      -server
      -printtoconsole
      -rpcbind=0.0.0.0:18443
      -rpcallowip=0.0.0.0/0
      -debug=1
      -zmqpubrawblock=tcp://*:28332
      -acceptnonstdtxn=0
      -addnode=BITCOIN_NODE_IP_PORT
    ports:
      - "18443:18443"
      - "28332:28332"
      - "18444:18444"